#!/usr/bin/env python

from __future__ import print_function
import string
import sys
import random


def main(argv):
    length = int(argv[0]) if argv else 6
    ascii = string.ascii_letters + string.digits + '@-_'

    print("".join([list(set(ascii))[random.randint(0, len(list(set(ascii))) - 1)]
                   for i in range(length)]), end='')


if __name__ == '__main__':
    main(sys.argv[1:])
